adjuntos/urls.py
from django.urls import re_path

from . import views

urlpatterns = [
    re_path(
        r"^(?P<attachment_id>\d+)/$",
        views.IdentificacionCreateView.as_view(),
        name="asignar-mesa",
    ),
    re_path(
        r"^(?P<attachment_id>\d+)/problema$",
        views.ReporteDeProblemaCreateView.as_view(),
        name="asignar-problema",
    ),
    re_path(
        r"^(?P<attachment_id>\d+)/editar-foto$", views.editar_foto, name="editar-foto"
    ),
    re_path(
        r"^agregar$",
        views.AgregarAdjuntosPreidentificar.as_view(),
        name="agregar-adjuntos",
    ),
    re_path(
        r"^ub/(?P<attachment_id>\d+)/$",
        views.IdentificacionCreateViewDesdeUnidadBasica.as_view(),
        name="asignar-mesa-ub",
    ),
    re_path(
        r"^ub/agregar$",
        views.AgregarAdjuntosDesdeUnidadBasica.as_view(),
        name="agregar-adjuntos-ub",
    ),
    re_path(
        r"^agregar-adjuntos-csv/$",
        views.AgregarAdjuntosCSV.as_view(),
        name="agregar-adjuntos-csv",
    ),
    re_path(
        r"^status-importacion-csv/(?P<csv_id>\d+)$",
        views.status_importacion_csv,
        name="status-importacion-csv",
    ),
]

api/urls.py
# -*- coding: utf-8 -*-
from django.urls import path, re_path

from rest_framework import permissions

from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

from drf_yasg.views import get_schema_view
from drf_yasg import openapi

from . import views

swagger_info = openapi.Info(
    title="La API del escrutinio del Frente de Tod☀s",
    default_version='v1',
    # description="Escrutinio social paralelo / Democracia con códigos",
    # license=openapi.License(name="GPLv3 License"),
)

schema_view = get_schema_view(swagger_info, public=True, permission_classes=(permissions.AllowAny, ))

urlpatterns = [
    path('actas/', views.subir_acta, name='actas'),
    path('actas/<foto_digest>/', views.identificar_acta, name='identificar-acta'),
    path('actas/<int:id_mesa>/votos/', views.cargar_votos, name='cargar-votos'),
    path('categorias/', views.listar_categorias, name='categorias'),
    path('categorias/<int:id_categoria>/opciones/', views.listar_opciones, name='opciones'),
    re_path(r'^token/$', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    re_path(r'^token/refresh/$', TokenRefreshView.as_view(), name='token_refresh'),
    re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    re_path(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    re_path(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc')
]

escrutinio_social/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import re_path
from django.conf.urls import include
from django.contrib import admin
from django.contrib.auth import views as auth_views

from fancy_cache import cache_page

from material.frontend import urls as frontend_urls

from elecciones import urls as elecciones_urls

from problemas import urls as problemas_urls

from fiscales import urls as fiscales_urls
from fiscales.views import (
    choice_home,
    confirmar_email,
    EnviarEmail,
    permission_denied,
    quiero_validar_gracias,
    QuieroSerFiscal,
)
from fiscales.forms import AuthenticationFormCustomError

from api import urls as api_urls
from antitrolling import urls as antitrolling_urls

cached = cache_page(3600 * 24 * 30)

urlpatterns = [
    re_path(r'^$', choice_home, name="home"),
    re_path(r'^permission-denied$', permission_denied, name='permission-denied'),
    re_path(r'^quiero-validar/(?P<codigo_ref>\w+)?$', QuieroSerFiscal.as_view(), name='quiero-validar'),
    re_path(r'^quiero-validar/gracias/$', quiero_validar_gracias, name='quiero-validar-gracias'),
    re_path(r'^quiero-validar/confirmar-email/(?P<uuid>[0-9a-f-]+)$', confirmar_email, name='confirmar-email'),
    re_path(r'^login/$', auth_views.LoginView.as_view(
        authentication_form=AuthenticationFormCustomError
    ), name='login'),
    re_path(r'', include(frontend_urls)),
    re_path(r'', include('django.contrib.auth.urls')),
    re_path(r'^hijack/', include('hijack.urls')),
    re_path('^admin/enviar_email$', EnviarEmail.as_view(), name='enviar-email'),
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^fiscales/', include(fiscales_urls)),

    re_path(r'^elecciones/', include(elecciones_urls)),
    re_path(r'^clasificar-actas/', include('adjuntos.urls')),

    re_path(r'^api/', include(api_urls)),
    re_path(r'^problemas/', include(problemas_urls)),
    re_path(r'^antitrolling/', include(antitrolling_urls)),
    re_path(r'^summernote/', include('django_summernote.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    if settings.USAR_DJANGO_DEBUG_TOOLBAR:
        import debug_toolbar
        from django.urls import include, path
        urlpatterns = [
            path('__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns
        SHOW_TOOLBAR_CALLBACK = True

fiscales/forms.py
from functools import partial
from django.conf import settings
from django import forms
from django.forms import modelformset_factory, BaseModelFormSet
from material import Layout, Row, Fieldset
from localflavor.ar.forms import ARDNIField
from django.contrib.auth.forms import AuthenticationForm
from django.utils.translation import ugettext_lazy as _
from django.core.validators import ValidationError, MinLengthValidator, MaxLengthValidator
from django.contrib.auth import password_validation
from django.template import engines
from datetime import timedelta
from django.utils import timezone
from django.utils.html import format_html

from django_summernote.widgets import SummernoteWidget
from django.utils.safestring import mark_safe

from dal import autocomplete

import phonenumbers

from .models import Fiscal
from django.contrib.auth.models import User
from elecciones.models import VotoMesaReportado, Categoria, Opcion, Distrito, Seccion
from .widgets import Select as OpcionLista

class AuthenticationFormCustomError(AuthenticationForm):
    error_messages = {
        'invalid_login': (
            'Por favor introduzca un nombre de usuario y una contraseña correctos. '
            'Probá tu DNI sin puntos, guiones ni espacios.'
        ),
        'inactive':
        _("This account is inactive."),
    }
    already_logged_message = (
        format_html('Ya hay un usuario sesionado/a con esta cuenta. Si sos vos mismo/a esperá '
        f'{int(settings.SESSION_TIMEOUT / 60)} minutos y volvé a intentarlo. '
        'También podés probar <a href="/logout">cerrando sesión</a>.')
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].label = 'Nombre de usuario o DNI'

    def confirm_login_allowed(self, user):
        try:
            fiscal = user.fiscal
            session_existente = fiscal.session_key
            last_seen = fiscal.last_seen
            ahora = timezone.now()
            timeout = last_seen + timedelta(seconds=settings.SESSION_TIMEOUT) if last_seen else None
            if session_existente and last_seen and ahora < timeout:
                raise forms.ValidationError(
                    _(self.already_logged_message),
                    code='already_logged'
                )
        except Fiscal.DoesNotExist:
            # no es usuario fiscal.
            pass
        return super().confirm_login_allowed(user)


def opciones_actuales():
    try:
        return Categoria.opciones_actuales().count()
    except Exception:
        return 0


class FiscalForm(forms.ModelForm):

    dni = ARDNIField(required=False)

    class Meta:
        model = Fiscal
        exclude = ()


class ReferidoForm(forms.Form):
    url = forms.CharField()
    url.label = ''

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['url'].widget.attrs['readonly'] = True


class MisDatosForm(FiscalForm):

    class Meta:
        model = Fiscal
        fields = [
            'nombres',
            'apellido',
            'tipo_dni',
            'dni',
        ]


class FiscalFormSimple(FiscalForm):

    class Meta:
        model = Fiscal
        fields = ['nombres', 'apellido', 'dni']


class CustomModelChoiceField(forms.ModelChoiceField):

    def label_from_instance(self, obj):
        return obj.label_from_instance


class FiscalxDNI(forms.ModelForm):
    dni = ARDNIField(required=True)


class QuieroSerFiscalForm(forms.Form):

    MENSAJE_ERROR_CODIGO_REF = 'Codigo de referido debe ser de 4 letras y/o números.'
    MENSAJE_ERROR_TELEFONO_INVALIDO = 'Teléfono no es válido. Chequeá código de área y teléfono.'
    MENSAJE_ERROR_DNI_REPETIDO = 'Ya se encuentra un usuario registrado con ese DNI.'
    MENSAJE_ERROR_PASSWORD_NO_IGUALES = "Las contraseñas no coinciden."
    MENSAJE_ERROR_EMAIL_REPETIDO = 'Ya existe ese correo. Intentá recuperando la contraseña'

    CARACTERES_REF_CODIGO = 4
    CANTIDAD_DIGITOS_NUMERACION_ARGENTINA = 10

    MAX_DIGITOS_TELEFONO_LOCAL = 8
    MIN_DIGITOS_TELEFONO_LOCAL = 5
    MAX_DIGITOS_COD_AREA = 5
    MIN_DIGITOS_COD_AREA = 2

    email = forms.EmailField(required=True)
    email_confirmacion = forms.EmailField(required=True, label="Confirmar email")
    apellido = forms.CharField(required=True, label="Apellido", max_length=50)
    nombres = forms.CharField(required=True, label="Nombres", max_length=100)
    dni = ARDNIField(required=True, label="DNI", help_text='Ingresá tu Nº de documento sin puntos.')
    telefono_area = forms.CharField(
        label='Código de área (sin 0 adelante).',
        help_text='Por ejemplo: 11 para CABA, 221 para La Plata, 351 para Córdoba, etc.',
        required=True,
        validators=[
            MaxLengthValidator(MAX_DIGITOS_COD_AREA),
            MinLengthValidator(MIN_DIGITOS_COD_AREA),
        ]
    )
    telefono_local = forms.CharField(
        label='Teléfono',
        help_text='Ingresá tu teléfono sin el 15, ni guiones ni espacios.',
        required=True,
        validators=[
            MaxLengthValidator(MAX_DIGITOS_TELEFONO_LOCAL),
            MinLengthValidator(MIN_DIGITOS_TELEFONO_LOCAL),
        ]
    )

    distrito = forms.ModelChoiceField(
        required=True,
        label='Provincia',
        queryset=Distrito.objects.all().order_by('numero'),
        widget=autocomplete.ModelSelect2(
            url='autocomplete-distrito-simple',
        ),
    )

    seccion = forms.ModelChoiceField(
        queryset=Seccion.objects.all(),
        required=False,
        widget=autocomplete.ModelSelect2(
            url='autocomplete-seccion-simple',
            forward=['distrito']
        ),
    )

    referente_nombres = forms.CharField(
        required=False, label="Nombre del referente", max_length=100,
        help_text="Si no tenés, dejalo en blanco."
    )
    referente_apellido = forms.CharField(
        required=False, label="Apellido del referente", max_length=50,
        help_text="Si no tenés, dejalo en blanco."
    )

    referido_por_codigo = forms.CharField(
        required=False,
        label="Código de referencia",
        help_text="Si no sabes qué es, dejalo en blanco."
    )

    password = forms.CharField(
        label='Elegí una contraseña',
        help_text='No uses la de tu email o redes sociales',
        widget=forms.PasswordInput,
        strip=False,
    )
    password_confirmacion = forms.CharField(
        label='Repetir la contraseña',
        strip=False,
        widget=forms.PasswordInput,
    )

    layout = Layout(
        Fieldset(
            'Datos personales',
            Row('nombres', 'apellido', 'dni'),
            Row('email', 'email_confirmacion'),
            Row('password', 'password_confirmacion'),
            Row('distrito', 'seccion')
        ),
        Fieldset(
            'Teléfono celular',
            Row('telefono_area', 'telefono_local')
        ),
        Fieldset(
            'Referencia',
            Row('referente_nombres', 'referente_apellido', 'referido_por_codigo')
        )
    )

    def clean(self):
        cleaned_data = super().clean()
        self.validar_correo(cleaned_data)
        self.validar_telefono(cleaned_data.get('telefono_area'), cleaned_data.get('telefono_local'))

    def clean_telefono_area(self):
        telefono_area = self.cleaned_data.get('telefono_area')
        if telefono_area:
            # por las dudas, sacamos los 0 a la izquierda del código de área
            telefono_area = telefono_area.lstrip('0')
        return telefono_area

    def validar_correo(self, cleaned_data):
        email = cleaned_data.get('email')
        email2 = cleaned_data.get('email_confirmacion')
        if email and email2 and email != email2:
            self.add_error('email', 'Los emails no coinciden')
            self.add_error('email_confirmacion', 'Los emails no coinciden')

        if User.objects.filter(email=email).exists():
            self.add_error('email', self.MENSAJE_ERROR_EMAIL_REPETIDO)

    def validar_telefono(self, telefono_area, telefono_local):
        if telefono_area and telefono_local:
            cantidad_digitos_telefono = len(telefono_area) + len(telefono_local)
            if cantidad_digitos_telefono != self.CANTIDAD_DIGITOS_NUMERACION_ARGENTINA:
                error = (
                    "Revisá el código de área y teléfono."
                    f"Entre ambos deben ser {self.CANTIDAD_DIGITOS_NUMERACION_ARGENTINA} números"
                )
                self.add_error('telefono_area', error)
                self.add_error('telefono_local', error)
            telefono = telefono_area + telefono_local
            valor = phonenumbers.parse(telefono, 'AR')
            if not phonenumbers.is_valid_number(valor):
                self.add_error(
                    'telefono_local',
                    self.MENSAJE_ERROR_TELEFONO_INVALIDO
                )
                self.add_error(
                    'telefono_area',
                    self.MENSAJE_ERROR_TELEFONO_INVALIDO
                )

    def clean_referente_apellido(self):
        return self.cleaned_data.get('referente_apellido', '').strip() or None

    def clean_referente_nombres(self):
        return self.cleaned_data.get('referente_nombres', '').strip() or None

    def clean_password(self):
        password = self.cleaned_data.get('password')
        if password:
            password_validation.validate_password(password)
        return password

    def clean_password_confirmacion(self):
        password = self.cleaned_data.get('password')
        password_confirmacion = self.cleaned_data.get('password_confirmacion')
        if password and password_confirmacion:
            if password != password_confirmacion:
                raise forms.ValidationError(self.MENSAJE_ERROR_PASSWORD_NO_IGUALES)
        return password_confirmacion

    def clean_dni(self):
        dni = self.cleaned_data.get('dni')
        if Fiscal.objects.filter(dni=dni).exists():

adjuntos/views/agregar_adjuntos_ub.py
from django.contrib import messages
from django.shortcuts import redirect
from django.urls import reverse
from django.db import transaction

import structlog

from adjuntos.forms import (
    AgregarAttachmentsForm,
    PreIdentificacionForm
)
from .agregar_adjuntos import AgregarAdjuntos

logger = structlog.get_logger(__name__)

MENSAJE_NINGUN_ATTACHMENT_VALIDO = 'Ningún archivo es válido o nuevo.'
MENSAJE_SOLO_UN_ACTA = 'Se debe subir una sola acta.'


class AgregarAdjuntosDesdeUnidadBasica(AgregarAdjuntos):
    """
    Permite subir una imagen, genera la instancia de Attachment y debería redirigir al flujo de
    asignación de mesa -> carga de datos pp -> carga de datos secundarios , etc

    Si una imagen ya existe en el sistema, se exluye con un mensaje de error
    via `messages` framework.
    """
    form_class = AgregarAttachmentsForm
    url_to_post = 'agregar-adjuntos-ub'
    template_name = 'adjuntos/agregar-adjuntos.html'

    def post(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        files = request.FILES.getlist('file_field')

        # No debería poder cargarse por UI más de una imagen, pero por las dudas lo chequeamos.

        if len(files) > 1:
            form.add_error('file_field', MENSAJE_SOLO_UN_ACTA)

        if form.is_valid():
            file = files[0]
            fiscal = request.user.fiscal
            with transaction.atomic():
                instance = self.procesar_adjunto(file, fiscal)
                if instance is not None:
                    messages.success(self.request, 'Subiste el acta correctamente.')
                    fiscal.asignar_attachment(instance)
                    instance.asignar_a_fiscal()
                    return redirect(reverse('asignar-mesa-ub', kwargs={"attachment_id": instance.id}))

            form.add_error('file_field', MENSAJE_NINGUN_ATTACHMENT_VALIDO)
        return self.form_invalid(form)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({'es_multiple': False})
        return kwargs

adjuntos/templates/adjuntos/agregar-adjuntos-csv.html
{% extends "adjuntos/agregar-adjuntos.html" %}
{% load i18n material_form material_frontend %}
{% load static %}

{% block page_title %}Subir archivos CSV{% endblock %}
{% block page_subtitle %}Cargar CSV{% endblock %}
{% block breadcrumbs_items %}<a href="{% static 'formato_csv.csv' %}">Archivo template CSV</a>{% endblock breadcrumbs_items %}
{% block card-title %}Subir CSV{% endblock card-title %}
{% block button_text %}Subir{% endblock button_text %}

adjuntos/templates/adjuntos/agregar-adjuntos-ub.html
{% extends "fiscales/base.html" %}
{% load i18n material_form material_frontend %}
{% load staticfiles %}

{% block page_title %}Subir actas desde UB{% endblock %}

{% block left-panel %}
<div class="card">

    <div class="card-content">

        <div class="card-title">{% block card-title %}
            Subir actas desde UB
            {% endblock card-title %}</div>

        <form action="{{ url_to_post }}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {# FIXME django-material desactiva el atributo multiple del filefield #}
            {# {% form  %}{% endform %} #}
            {{ attachment_form }}

            <div class="card-title">¿De qué mesa es esta acta?</div>
                  {% include "adjuntos/asignar-mesa-form.html" with form=identificacion_form %}
            </div>
	    
            <div class="card-action">
                <div class="right-align">
                    {% block submit_row %}
                    <button type="submit" class="waves-effect waves-light btn white-text">Subir</button>
                    {% endblock %}
                </div>
            </div>
        </form>

    </div>
</div>
{% endblock %}

adjuntos/templates/adjuntos/asignar-mesa-ub.html
{% extends "adjuntos/asignar-mesa.html" %}

{% block asignar-mesa-actions %}
<a class="btn waves-effect waves-light btn brown lighten-2 white-text" href="{% url 'agregar-adjuntos-ub' %}">
    Subir otra acta
    <i class="material-icons right">cloud_upload</i>
</a>
<button class="btn waves-effect waves-light btn white-text" type="submit" tabindex="{{ button_tabindex }}">
    Cargar datos
</button>
{% endblock asignar-mesa-actions %}

adjuntos/templates/adjuntos/asignar-mesa.html
{% extends "fiscales/base.html" %}
{% load l10n i18n material_form material_frontend %}
{% load static %}

{% block breadcrumbs_items %}
<a href="{{ object.get_absolute_url }}">{{ object }}</a>
<a class="active">Acta</a>
<a href="{{ url_video_instructivo }}" id="btnVideoInstructivo">Video instructivo<i class="material-icons">videocam</i></a>

<div id="modalVideoInstructivo" class="modal-video">
 <!-- Video instructivo como ventana modal. -->
  <div class="modal-content video">
    <span class="close-modal-content">&times;</span>
     <iframe width="854" height="480" src="{{ url_video_instructivo }}">
     </iframe>
  </div>
</div>
{% endblock %}
{% block js %}
{{ block.super }}
<script src="{% static 'js/sidenav.js' %}"></script>
<script src="{% static 'js/simpleselect.js' %}"></script>
<script src="{% static 'js/commons.js' %}"></script>
{% block extrajs %}{% endblock %}
{% endblock %}

{% block extrahead %}
<style type="text/css">
.resultado-select{
    border-bottom: none !important;
}

.requerido > label {
    font-weight: 600 !important;
    color: light-gray;
}
.content {
  padding-bottom: 0px;
}

.left-panel {

  flex-basis: 30%;
  margin-left: 0.375rem; }
  .left-panel.wide {
    flex-basis: 100%;
    margin-right: 0.375rem; }
  .left-panel > .card {
    margin-bottom: 0.375rem; }


.left-panel > .input_field input{
  height: 2rem;
}

.right-panel {
  flex-basis: 70%;
  min-width: 350px;
  margin-left: 0.375rem;
  margin-right: 0.375rem;
}
.right-panel > .card {
    margin-bottom: 0.5rem;
}


@media only screen and (max-width: 993px) {
  .left-panel {
    flex-basis: 100%;
    width: 100%;
    margin-left: 0;
    margin-right: 0;
  }
  .left-panel > .card {
    margin-top: 1px;
  }
}

/* The Modal (background) */
.modal-video {
  display: none; /* Hidden by default */
  position: fixed; /* Stay in place */
  z-index: 1000; /* Sit on top */
  padding-top: 30px; /* Location of the box */
  left: 0;
  top: 0;
  width: 80%; /* Full width */
  height: 100%; /* Full height */
  overflow: auto; /* Enable scroll if needed */
  background-color: rgb(0,0,0); /* Fallback color */
  background-color: rgba(0,0,0,0.4); /* Black w/ opacity */

}
/* Modal Content */
.modal-content.video {
  background-color: #fefefe;
  margin: auto;
  padding: 9px !important;
  border: 1px solid #888;
  width: 90%;
}
/* The Close Button */
.close-modal-content {
  color: #aaaaaa;
  float: right;
  font-size: 28px;
  font-weight: bold;
}
.close-modal-content:hover,
.close-modal-content:focus {
  color: #000;
  text-decoration: none;
  cursor: pointer;
}


</style>
{% endblock %}


{% block page_title %}Clasificar fotos de actas{% endblock %}

{% block left-panel %}
  <div class="card">
      <form method="POST" enctype="multipart/form-data" {% if action %}action="{{action}}"{% endif %}>
          {% csrf_token %}
          <div class="card-content">
            {% block card-content %}
              <div class="card-title">¿De qué mesa es esta acta?</div>
              {% form %}
	      {% endform %}
        {% if form.errors %}
	      <div class="grey-text text-darken-1">Si no podés identificar la imagen, podés
		reportarlo con el botón “Problema”.</div>
	      {% endif %}
            {% endblock card-content %}
          </div>
          <div class="card-action">
            {% block card-action %}
            <div class="right-align">
              <button id="boton-enviar" class="btn waves-effect waves-light btn white-text" type="submit" tabindex="5">
                Guardar
              </button>
              <a  class="waves-effect waves-light btn white-text modal-trigger red" href="#modal-problem" id="btn-problema">
                Problema
	      </a>
            </div>
            {% endblock card-action %}
          </div>
      </form>
  </div>
  {% block information %}
  {% endblock information %}

  {% if recibir_problema %}
  {% include "problemas/problema.html" %}
  {% endif %}
{% endblock left-panel %}

{% block head %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static 'css/darkroom.css' %}" />
{% endblock %}



{% block right-panel %}
    <div class="acta card">
        <div class="card-content">
            <img id="target" src="{{ attachment.foto.thumbnail.960x.url }}">

            <script src="{% static 'js/fabric.js' %}"></script>
            <script src="{% static 'js/darkroom.js' %}"></script>
            <script>
            new Darkroom('#target', {
              plugins: {
                save: {
                  callback: function() {
                    var newImage = this.darkroom.canvas.toDataURL();
                    $.post("{% url 'editar-foto' attachment.id %}", {data: newImage}, function(data){
                       M.toast({ html: data.message});
                    })
                  }
                }
              },

              /*
                corremos el seteo del height después de la inicialización de Darkroom.
                antes a veces no se seteaba el height del contenedor porque Darkroom no había terminado de cargar
                el evento ready se tiraba, pero luego Darkroom asincrónicamente cambia el HTML, entonces había una condición de carrera
                el seteo ahora se hace en initialize, que es un callback que nos da Darkroom
                */
              initialize: function() {
                calcularYSetearAlturaContenedorDarkroom();
              },
            });
            </script>
        </div>
    </div>
{% endblock right-panel %}

{% block messages %}
{{ block.super }}
{{ form.media }}
<script type="text/javascript">
  var url_distrito = "{% url 'autocomplete-distrito' %}";
  var url_seccion  = "{% url 'autocomplete-seccion' %}";
  var url_circuito = "{% url 'autocomplete-circuito' %}";
  var url_mesa = "{% url 'autocomplete-mesa' %}";
  var fields = [
      ['distrito', updateDistrito(url_distrito, ocultoSeccionCircuito),url_distrito,[]]
  ];

  $(document).ready(function(){
      $('.modal').modal();
      fields.map(e => (e[2]) ? initializeSimpleSelect(e[0],e[2], ocultoSeccionCircuito) : null);
      fields.map(e => $('#'+e[0]+'_input').on("keyup",delay(e[1], 300)));

      $('#distrito_input').attr('tabindex', 1);
      $('#id_seccion').attr('tabindex', 2);
      $('#id_circuito').attr('tabindex', 3);
      $('#id_mesa').attr('tabindex', 4);

      if($('#distrito_input').val() == "") {
        $('#distrito_input').focus();
      } else if($('#id_seccion').val() == "") {
	      $('#id_seccion').focus();
      } else if($('#id_circuito').val()==""){
	      $('#id_circuito').focus();
      } else if($('#id_mesa').val()==""){
	      $('#id_mesa').focus();
      };
      $('#btn-reportar').on('click',function(e){
	  var form = $('#problema-imagen');
	  $.ajax({
            type: $(form).attr('method'),
            url: $(form).attr('action'),
            data: form.serialize(),
            context: form,
            success: function(data, status) {
              $(form).submit();
            },
            error: function (request, type, errorThrown) {
              var json = $.parseJSON(request.responseText);
              $.map(json, function( val, i ) {
                if(val){
                  $('#'+i).removeClass('hide');
                }
              });
            }
	  });
	  return false;
      });
  // Get the modal
  var modal_video_instructivo = document.getElementById("modalVideoInstructivo");

  // Get the button that opens the modal
  var btn_video_instructivo = document.getElementById("btnVideoInstructivo");

  // Get the <span> element that closes the modal
  var close_span = document.getElementsByClassName("close-modal-content")[0];

  primer_ingreso = "{{ request.user.fiscal.ingreso_alguna_vez }}" == "False" ? true : false
  "{{ request.user.fiscal.marcar_ingreso_alguna_vez }}"

  if (primer_ingreso) {
    modal_video_instructivo.style.display = "block";
  }

  // When the user clicks the button, open the modal
  btn_video_instructivo.onclick = function(event) {
    event.preventDefault()
    modal_video_instructivo.style.display = "block";
  }

  // When the user clicks on <span> (x), close the modal
  close_span.onclick = function(event) {
    modal_video_instructivo.style.display = "none";
  }

  // When the user clicks anywhere outside of the modal, close it
  window.onclick = function(event) {
    if (event.target == modal_video_instructivo) {
      modal_video_instructivo.style.display = "none";
    }
  }

  });
</script>

{% endblock messages %}